export const EQUIPOS = [
    {
        id: 0,
        nombre_equipo: 'Central Larroque',
        nombre_equipo_short: 'CCL',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1P26Jf401tdlqe7b8F1m-AF1we1v2__go&rl',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 1,
        nombre_equipo: 'Central Larroque',
        nombre_equipo_short: 'CCL',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1P26Jf401tdlqe7b8F1m-AF1we1v2__go&rl',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 2,
        nombre_equipo: 'Central Larroque',
        nombre_equipo_short: 'CCL',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1P26Jf401tdlqe7b8F1m-AF1we1v2__go&rl',
        division: 'copa gchu',
        categoria: 'grupo f',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 3,
        nombre_equipo: 'La Vencedora',
        nombre_equipo_short: 'VEN',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1IegVLDTlZM0x1J6yWNGc2RUykAfIDC2j&rl',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 4,
        nombre_equipo: 'La Vencedora',
        nombre_equipo_short: 'VEN',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1IegVLDTlZM0x1J6yWNGc2RUykAfIDC2j&rl',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 5,
        nombre_equipo: 'La Vencedora',
        nombre_equipo_short: 'VEN',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1IegVLDTlZM0x1J6yWNGc2RUykAfIDC2j&rl',
        division: 'copa gchu',
        categoria: 'grupo e',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 6,
        nombre_equipo: 'Black River',
        nombre_equipo_short: 'RIV',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1FpSPTA75lz3n9nF-2qVpKXSwszfp9WYw&rl',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 7,
        nombre_equipo: 'Black River',
        nombre_equipo_short: 'RIV',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1FpSPTA75lz3n9nF-2qVpKXSwszfp9WYw&rl',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 8,
        nombre_equipo: 'Black River',
        nombre_equipo_short: 'RIV',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1FpSPTA75lz3n9nF-2qVpKXSwszfp9WYw&rl',
        division: 'copa gchu',
        categoria: 'grupo c',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 9,
        nombre_equipo: 'Pueblo Nuevo',
        nombre_equipo_short: 'PN',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1MNZc1jaLNDW87yMZToCAdNACY-8buEZB&rl',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 10,
        nombre_equipo: 'Pueblo Nuevo',
        nombre_equipo_short: 'PN',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1MNZc1jaLNDW87yMZToCAdNACY-8buEZB&rl',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 11,
        nombre_equipo: 'Pueblo Nuevo',
        nombre_equipo_short: 'PN',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1MNZc1jaLNDW87yMZToCAdNACY-8buEZB&rl',
        division: 'copa gchu',
        categoria: 'grupo c',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 12,
        nombre_equipo: 'Deportivo Urdinarrain',
        nombre_equipo_short: 'CDU',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1Go0heMVpoM0zvSfM5NY2bbjHU6AuKQFG&rl',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 13,
        nombre_equipo: 'Deportivo Urdinarrain',
        nombre_equipo_short: 'CDU',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1Go0heMVpoM0zvSfM5NY2bbjHU6AuKQFG&rl',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 14,
        nombre_equipo: 'Deportivo Urdinarrain',
        nombre_equipo_short: 'CDU',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1Go0heMVpoM0zvSfM5NY2bbjHU6AuKQFG&rl',
        division: 'copa gchu',
        categoria: 'grupo c',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 15,
        nombre_equipo: 'Juventud Urdinarrain',
        nombre_equipo_short: 'JUV(U)',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1NAg6_C-qALiES2W-gYTinDVKPMKvO0YU&rl',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 16,
        nombre_equipo: 'Juventud Urdinarrain',
        nombre_equipo_short: 'JUV(U)',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1NAg6_C-qALiES2W-gYTinDVKPMKvO0YU&rl',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 17,
        nombre_equipo: 'Juventud Urdinarrain',
        nombre_equipo_short: 'JUV(U)',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1NAg6_C-qALiES2W-gYTinDVKPMKvO0YU&rl',
        division: 'copa gchu',
        categoria: 'grupo e',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 18,
        nombre_equipo: 'Juventud Unida',
        nombre_equipo_short: 'JUV(G)',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=11lsmEfOfdYZlQBNm09q5BNw52uEOcQIr&rl',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 19,
        nombre_equipo: 'Juventud Unida',
        nombre_equipo_short: 'JUV(G)',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=11lsmEfOfdYZlQBNm09q5BNw52uEOcQIr&rl',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 20,
        nombre_equipo: 'Juventud Unida',
        nombre_equipo_short: 'JUV(G)',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=11lsmEfOfdYZlQBNm09q5BNw52uEOcQIr&rl',
        division: 'copa gchu',
        categoria: 'grupo a',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 21,
        nombre_equipo: 'Central Entrerriano',
        nombre_equipo_short: 'CCE',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=11hfYivMo2ytdLCEm4yaYQpJhWRsSmaAS&rl',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 22,
        nombre_equipo: 'Central Entrerriano',
        nombre_equipo_short: 'CCE',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=11hfYivMo2ytdLCEm4yaYQpJhWRsSmaAS&rl',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 23,
        nombre_equipo: 'Central Entrerriano',
        nombre_equipo_short: 'CCE',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=11hfYivMo2ytdLCEm4yaYQpJhWRsSmaAS&rl',
        division: 'copa gchu',
        categoria: 'grupo d',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 24,
        nombre_equipo: 'Sud America',
        nombre_equipo_short: 'SUD',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1YV17DpQHOre5YXORh_1LaLxxTYRH4nSh&rl',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 25,
        nombre_equipo: 'Sud America',
        nombre_equipo_short: 'SUD',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1YV17DpQHOre5YXORh_1LaLxxTYRH4nSh&rl',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 26,
        nombre_equipo: 'Sud America',
        nombre_equipo_short: 'SUD',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1YV17DpQHOre5YXORh_1LaLxxTYRH4nSh&rl',
        division: 'copa gchu',
        categoria: 'grupo a',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 27,
        nombre_equipo: 'Sarmiento',
        nombre_equipo_short: 'SAR',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1kdTaCIM3lRC0pSHPFN_ByVCNA4zfBCss&rl',
        division: 'a',
        pts: 0,
        categoria: 'primera',
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 28,
        nombre_equipo: 'Sarmiento',
        nombre_equipo_short: 'SAR',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1kdTaCIM3lRC0pSHPFN_ByVCNA4zfBCss&rl',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 29,
        nombre_equipo: 'Sarmiento',
        nombre_equipo_short: 'SAR',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1kdTaCIM3lRC0pSHPFN_ByVCNA4zfBCss&rl',
        division: 'copa gchu',
        categoria: 'grupo b',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 30,
        nombre_equipo: 'Defensores del Oeste',
        nombre_equipo_short: 'DEF',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1Y_f2YfbmuqnvKCApYGKRg7OUSWQ03B-7&rl',
        division: 'a',
        categoria:'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 31,
        nombre_equipo: 'Defensores del Oeste',
        nombre_equipo_short: 'DEF',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1Y_f2YfbmuqnvKCApYGKRg7OUSWQ03B-7&rl',
        division: 'a',
        categoria:'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 32,
        nombre_equipo: 'Defensores del Oeste',
        nombre_equipo_short: 'DEF',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1Y_f2YfbmuqnvKCApYGKRg7OUSWQ03B-7&rl',
        division: 'copa gchu',
        categoria:'grupo d',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 33,
        nombre_equipo: 'Cerro Porteño',
        nombre_equipo_short: 'CP',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1TObXJ0q7QyFczSwcPR_jSXu0HYbiDuMO&rl',
        division: 'b',
        categoria:'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 34,
        nombre_equipo: 'Cerro Porteño',
        nombre_equipo_short: 'CP',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1TObXJ0q7QyFczSwcPR_jSXu0HYbiDuMO&rl',
        division: 'b',
        categoria:'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 35,
        nombre_equipo: 'Cerro Porteño',
        nombre_equipo_short: 'CP',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1TObXJ0q7QyFczSwcPR_jSXu0HYbiDuMO&rl',
        division: 'copa gchu',
        categoria:'grupo b',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 36,
        nombre_equipo: 'Union',
        nombre_equipo_short: 'UNI',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1wtqoQU16NVfUibLUNxNwDo1yXH1KxyLP&rl',
        division: 'b',
        categoria:'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 37,
        nombre_equipo: 'Union',
        nombre_equipo_short: 'UNI',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1wtqoQU16NVfUibLUNxNwDo1yXH1KxyLP&rl',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 38,
        nombre_equipo: 'Union',
        nombre_equipo_short: 'UNI',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1wtqoQU16NVfUibLUNxNwDo1yXH1KxyLP&rl',
        division: 'copa gchu',
        categoria:'grupo c',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 39,
        nombre_equipo: 'La Ribera',
        nombre_equipo_short: 'RIB',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1BOyy4UtJMgCfz2taJcqZLCRrif5qh1xy&rl',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 40,
        nombre_equipo: 'La Ribera',
        nombre_equipo_short: 'RIB',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1BOyy4UtJMgCfz2taJcqZLCRrif5qh1xy&rl',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 41,
        nombre_equipo: 'La Ribera',
        nombre_equipo_short: 'RIB',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1BOyy4UtJMgCfz2taJcqZLCRrif5qh1xy&rl',
        division: 'copa gchu',
        categoria: 'grupo f',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 42,
        nombre_equipo: 'Sporting',
        nombre_equipo_short: 'SPO',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1xgBIgGutafyoJec08WovA4e15Fnuienc&rl',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 43,
        nombre_equipo: 'Sporting',
        nombre_equipo_short: 'SPO',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1xgBIgGutafyoJec08WovA4e15Fnuienc&rl',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 44,
        nombre_equipo: 'Sporting',
        nombre_equipo_short: 'SPO',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1xgBIgGutafyoJec08WovA4e15Fnuienc&rl',
        division: 'copa gchu',
        categoria: 'grupo b',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 45,
        nombre_equipo: 'Juvenil del Norte',
        nombre_equipo_short: 'JDN',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1_F3U_mOtsbmxH8BgadqpiSGy0DyPH8R6&rl',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 46,
        nombre_equipo: 'Juvenil del Norte',
        nombre_equipo_short: 'JDN',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1_F3U_mOtsbmxH8BgadqpiSGy0DyPH8R6&rl',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 47,
        nombre_equipo: 'Juvenil del Norte',
        nombre_equipo_short: 'JDN',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1_F3U_mOtsbmxH8BgadqpiSGy0DyPH8R6&rl',
        division: 'copa gchu',
        categoria: 'grupo e',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 48,
        nombre_equipo: 'Deportivo Gurises',
        nombre_equipo_short: 'GUR',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1ZqVHg0xQxcyvH2KWk5iJypCjsMFd_p3U&rl',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 49,
        nombre_equipo: 'Deportivo Gurises',
        nombre_equipo_short: 'GUR',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1ZqVHg0xQxcyvH2KWk5iJypCjsMFd_p3U&rl',
        division: 'copa gchu',
        categoria: 'grupo a',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 50,
        nombre_equipo: 'Deportivo Gurises',
        nombre_equipo_short: 'GUR',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1ZqVHg0xQxcyvH2KWk5iJypCjsMFd_p3U&rl',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 51,
        nombre_equipo: 'Deportivo Gurises',
        nombre_equipo_short: 'GUR',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1ZqVHg0xQxcyvH2KWk5iJypCjsMFd_p3U&rl',
        division: 'copa gchu',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 52,
        nombre_equipo: 'Independiente',
        nombre_equipo_short: 'CAI',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1XD_EnZIX5D2SXfg37D8f7mV3yGWikk0t&rl',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 53,
        nombre_equipo: 'Independiente',
        nombre_equipo_short: 'CAI',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1XD_EnZIX5D2SXfg37D8f7mV3yGWikk0t&rl',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 54,
        nombre_equipo: 'Independiente',
        nombre_equipo_short: 'CAI',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1XD_EnZIX5D2SXfg37D8f7mV3yGWikk0t&rl',
        division: 'copa gchu',
        categoria: 'grupo d',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 55,
        nombre_equipo: 'Sportivo Larroque',
        nombre_equipo_short: 'CSL',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=19qxoEhQZb9SbWrDe0jQegsVmlhx_ANYv&rl',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 56,
        nombre_equipo: 'Sportivo Larroque',
        nombre_equipo_short: 'CSL',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=19qxoEhQZb9SbWrDe0jQegsVmlhx_ANYv&rl',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 57,
        nombre_equipo: 'Sportivo Larroque',
        nombre_equipo_short: 'CSL',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=19qxoEhQZb9SbWrDe0jQegsVmlhx_ANYv&rl',
        division: 'copa gchu',
        categoria: 'grupo b',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 58,
        nombre_equipo: 'Camioneros',
        nombre_equipo_short: 'CAM',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=12Nbhk3LhZcbrLqnhFVypE5uuaHeYg7yb&rl',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 59,
        nombre_equipo: 'Camioneros',
        nombre_equipo_short: 'CAM',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=12Nbhk3LhZcbrLqnhFVypE5uuaHeYg7yb&rl',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 60,
        nombre_equipo: 'Camioneros',
        nombre_equipo_short: 'CAM',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=12Nbhk3LhZcbrLqnhFVypE5uuaHeYg7yb&rl',
        division: 'copa gchu',
        categoria: 'grupo f',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 61,
        nombre_equipo: 'Isleños Independientes',
        nombre_equipo_short: 'ISL',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1IvDz3hvuynC7ULRJHctcMlhvznD1dxWR&rl',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 62,
        nombre_equipo: 'Isleños Independientes',
        nombre_equipo_short: 'ISL',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1IvDz3hvuynC7ULRJHctcMlhvznD1dxWR&rl',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 63,
        nombre_equipo: 'Isleños Independientes',
        nombre_equipo_short: 'ISL',
        escudo_equipo: 'https://drive.google.com/uc?export=view&id=1IvDz3hvuynC7ULRJHctcMlhvznD1dxWR&rl',
        division: 'copa gchu',
        categoria: 'grupo a',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
];